name = "nuxt3-demo-playground"
type = "javascript"
account_id = "681d6ab8c912f39032027919f5d44a56"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "NITRO_PRESET=cloudflare yarn nuxt build"
upload.format = "service-worker"
